force_password_change.settings:
  type: config_object
  mapping:
    enabled:
      type: boolean
      label: 'Module Enabled'
    expire_password:
      type: boolean
      label: 'Expire Password'
    first_time_login_password_change:
      type: boolean
      label: 'Force password change on first time login'
    installation_date:
      type: integer
      label: 'Module installation date'
    check_login_only:
      type: boolean
      label: 'Check for force on login only'
